
<div class="ss-foot">

    <div class="ss-container">
        <hr class="sep">
        <div class="ss-foot-love">
            <a href="http://simple-works.org/simple-site">We ❤ Simple Site's</a>
        </div>
        <div class="ss-foot-menu fixed">
            <?php include('inc_menu.php'); ?>
        </div>
        <div class="ss-foot-copy">
            Copyright <?=date('Y')?> - <?=cfg('site.name')?>
        </div>
    </div>

</div><!-- .ss-foot -->

</body>
</html>