<!DOCTYPE html>
<html lang="<?=ss_get('language')?>">
<head>
    <title><?=ss_title()?></title>

    <meta charset="<?=ss_get('encoding')?>">
    <meta name="description" content="<?=ss_get('description')?>">

    <link rel="dns-prefetch" href="http://fonts.googleapis.com/">

    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Oswald:400,800">

    <link rel="stylesheet" href="<?=ss_asset('reset.css')?>">
    <link rel="stylesheet" href="<?=ss_asset('common.css')?>">
</head>
<body>

<div class="ss-head">

    <div class="ss-container">

        <div class="ss-head-menu fixed">
            <?php include('menu.php'); ?>
        </div>

    </div>

</div><!-- .ss-head -->
